name: Java CI
on: push
jobs:
    Clone-down:
      runs-on: ubuntu:latest
      container: gradle:6-jdk11
      steps:
      - name:
        uses: actions/checkout@v2
    Test:
      runs-on: ubuntu:latest
      needs: Clone-down
      container: gradle:6-jdk11
      steps: 
      - name:
      - run: ci/unit-test-app.sh
    Build:
      runs-on: ubuntu:latest
      needs: Clone-down
      container: gradle:6-jdk11
      steps: 
      - name: 
      - run: ci/build-app.sh